export const timezonesRu = {
	"International Date Line West": "Международная линия перемены дат Запад",
	"Midway Island": "Мидуэй",
	Samoa: "Самоа",
	"American Samoa": "Американское Самоа",
	Hawaii: "Гаваи",
	Alaska: "Аляска",
	"Pacific Time (US & Canada)": "Тихоокеанское время (США и Канада)",
	"Pacific Time": "Тихоокеанское время (США и Канада)",
	Tijuana: "Тихуана",
	"Mountain Time (US & Canada)": "Горное время (США и Канада)",
	"Mountain Time": "Горное время (США и Канада)",
	Arizona: "Аризона",
	Chihuahua: "Чихуахуа",
	Mazatlan: "Мазатлан",
	"Central Time (US & Canada)": "Центральное время (США и Канада)",
	"Central Time": "Центральное время (США и Канада)",
	Saskatchewan: "Саскачеван",
	Guadalajara: "Гвадалахара",
	"Mexico City": "Мехико",
	Monterrey: "Монтеррей",
	"Central America": "Центральная Америка",
	"Eastern Time (US & Canada)": "Центральная Америка",
	"Eastern Time": "Центральная Америка",
	"Indiana (East)": "Индиана (восток)",
	Bogota: "Богота",
	Lima: "Лима",
	Quito: "Кито",
	"Atlantic Time (Canada)": "Атлантическое время (Канада)",
	Caracas: "Каракас",
	"La Paz": "Ла-Пас",
	Santiago: "Сантьяго",
	Newfoundland: "Ньюфаундленд",
	Brasilia: "Бразилиа",
	"Buenos Aires": "Буэнос-Айрес",
	Georgetown: "Джорджтаун",
	Greenland: "Гренландия",
	"Mid-Atlantic": "Средне-атлантическое",
	Azores: "Азорские острова",
	"Cape Verde Is.": "Кабо-Верде.",
	Dublin: "Дублин",
	Edinburgh: "Эдинбург",
	Lisbon: "Лиссабон",
	London: "Лондон",
	Casablanca: "Касабланка",
	Monrovia: "Монровия",
	UTC: "UTC",
	Belgrade: "Белград",
	Bratislava: "Братислава",
	Budapest: "Будапешт",
	Ljubljana: "Любляна",
	Prague: "Прага",
	Sarajevo: "Сараево",
	Skopje: "Скопье",
	Warsaw: "Варшава",
	Zagreb: "Загреб",
	Brussels: "Брюссель",
	Copenhagen: "Копенгаген",
	Madrid: "Мадрид",
	Paris: "Париж",
	Amsterdam: "Амстердам",
	Berlin: "Берлин",
	Bern: "Берн",
	Rome: "Рим",
	Stockholm: "Стокгольм",
	Vienna: "Вена",
	"West Central Africa": "Западной и Центральной Африки",
	Bucharest: "Бухарест",
	Cairo: "Каир",
	Helsinki: "Хельсинки",
	Kyiv: "Киев",
	Riga: "Рига",
	Sofia: "София",
	Tallinn: "Таллин",
	Vilnius: "Вильнюс",
	Athens: "Афины",
	Istanbul: "Стамбул",
	Minsk: "Минск",
	Jerusalem: "Иерусалим",
	Harare: "Хараре",
	Pretoria: "Претория",
	Moscow: "Москва",
	"St. Petersburg": "Санкт-Петербург",
	Volgograd: "Волгоград",
	Kuwait: "Кувейт",
	Riyadh: "Рияд",
	Nairobi: "Найроби",
	Baghdad: "Багдад",
	Tehran: "Тегеран",
	"Abu Dhabi": "Абу-Даби",
	Muscat: "Мускат",
	Baku: "Баку",
	Tbilisi: "Тбилиси",
	Yerevan: "Ереван",
	Kabul: "Кабул",
	Ekaterinburg: "Екатеринбург",
	Islamabad: "Исламабад",
	Karachi: "Карачи",
	Tashkent: "Ташкент",
	Chennai: "Ченнаи",
	Kolkata: "Калькутта",
	Mumbai: "Мумбаи",
	"New Delhi": "Нью-Дели",
	Kathmandu: "Катманду",
	Astana: "Астана",
	Dhaka: "Дакка",
	"Sri Jayawardenepura": "Шри-Яварденапура",
	Almaty: "Алматы",
	Novosibirsk: "Новосибирск",
	Rangoon: "Рангун",
	Bangkok: "Бангкок",
	Hanoi: "Ханой",
	Jakarta: "Джакарта",
	Krasnoyarsk: "Красноярск",
	Beijing: "Пекин",
	Chongqing: "Чунцин",
	"Hong Kong": "Гонконг",
	Urumqi: "Урумчи",
	"Kuala Lumpur": "Куала-Лумпур",
	Singapore: "Сингапур",
	Taipei: "Тайбэй",
	Perth: "Перт",
	Irkutsk: "Иркутск",
	"Ulaan Bataar": "Улан-Батор",
	Seoul: "Сеул",
	Osaka: "Осака",
	Sapporo: "Саппоро",
	Tokyo: "Токио",
	Yakutsk: "Якутск",
	Darwin: "Дарвин",
	Adelaide: "Аделаида",
	Canberra: "Канберра",
	Melbourne: "Мельбурн",
	Sydney: "Сидней",
	Brisbane: "Брисбен",
	Hobart: "Хобарт",
	Vladivostok: "Владивосток",
	Guam: "Гуам",
	"Port Moresby": "Порт-Морсби",
	Magadan: "Магадан",
	"Solomon Is.": "Соломоновы острова.",
	"New Caledonia": "Новая Каледония",
	Fiji: "Фиджи",
	"Fiji Islands": "Острова Фиджи",
	Kamchatka: "Камчатка",
	"Marshall Is.": "Маршалловы о-ва",
	Auckland: "Окленд",
	Wellington: "Веллингтон",
	"Nuku'alofa": "Нукуалофа",
	"Tokelau Is.": "Токелау",
	Yukon: "Юкон",
	"Newfoundland and Labrador": "Ньюфа́ундленд и Лабрадо́р",
	Dawson: "Доусон",
};
