export enum Modules {
	Default = "default",
	Circles = "circles",
	Profile = "profile",
	Events = "events",
	DetailedEvent = "detailedEvent",
	Donuts = "donuts",
	DonutPreview = "donut_preview",
	Employees = "employees",
	EmployeePreview = "employee_preview",
	Requests = "requests",
	StoreManager = "store_manager",
	ShareAll = "share_all",
	ConfirmEmail = "confirm_email",
	AccessibleTenants = "accessible_tenants",
	MyTenants = "my_tenants",
	MyInvitations = "my_invitations",
}
