export enum texts_t {
	teams_you_can_join = "teams you can join",
	to = "to",
	to_profile = "to profile",
	to_store = "to store",
	transfer_type = "transfer type",
	transfer_points = "transfer points",
	transfer_donuts = "transfer donuts",
	transferred = "transferred",
	transfer = "transfer",
	time_is_required = "time is required",
	tooltip_scheduler_time = "tooltip_scheduler_time",
	total_donuts_received = "total received",
	total_donuts_sent = "total received",
	telegram_code = "telegram code",
}
