export enum texts_t {
	this_year = "this year",
	team_star = "team star",
	teams_you_can_join = "teams you can join",
	theme = "theme",
	theme_dark = "theme dark",
	theme_light = "theme light",
	theme_system = "theme system",
	track_your_requests_in_one_feed = "track your requests in one feed",
	to = "to",
	to_profile = "to profile",
	to_store = "to store",
	transfer_type = "transfer type",
	transfer_points = "transfer points",
	transfer_donuts = "transfer donuts",
	transferred = "transferred",
	transfer = "transfer",
	time_is_required = "time is required",
	tooltip_scheduler_time = "tooltip_scheduler_time",
	total_donuts_received = "total received",
	total_donuts_sent = "total received",
	total_rewards = "total rewards",
	telegram_code = "telegram code",
}
