export enum texts_c {
	"close" = "close",
	"closed" = "closed",
	coins = "coins",
	"cancel" = "cancel",
	"create" = "create",
	"created" = "created",
	"contact" = "Contact",
	"comment" = "comment",
	"comment_is_required" = "comment is required",
	"confirmation" = "confirmation",
	"confirm" = "confirm",
	"confirmed" = "confirmed",
	"confirm_email" = "confirm email",
	"closed_requests" = "closed requests",
	"choose_employees" = "choose employees",
	"choose_type" = "choose type",
	choose_day = "choose day",
	choose_time = "choose time",
	choose_timezone = "choose timezone",
	confirmation_email_was_sent_to = "confirmation email was sent to",
	connect_to_telegram = "connect to telegram",
	connect = "подключить",
}
