export enum texts_v {
	vk_auth_cancelled = "vk auth cancelled",
	vk_connecting_title = "Connecting VK...",
	vk_connecting_description = "Checking access and creating a session. This usually takes a couple of seconds.",
	vk_do_not_close = "Do not close this window.",
	vk_success_title = "Ready!",
	vk_success_description = "VK connected successfully. We will redirect you to Bonuts.",
	vk_login_connecting_title = "vk login connecting title",
	vk_login_connecting_description = "vk login connecting description",
	vk_login_success_description = "vk login success description",
	vk_login_error_title = "vk login error title",
	vk_error_title = "Unable to connect VK",
	vk_error_description = "It looks like a technical error occurred. Please try again.",
	vk_try_again = "Try again",
	vk_notifications_disabled_prefix = "Write a message to the VK group",
	vk_notifications_disabled_link = "here",
	vk_notifications_disabled_suffix = "then enable notifications.",
	view_all_invitations = "view all invitations",
}
