export enum texts_d {
	donuts_received_description = "donuts received description",
	day = "day",
	delivery_days = "delivery days",
	decline = "decline",
	declined = "declined",
	deactivate = "deactivate",
	description = "description",
	disable_account = "disable account",
	disabled = "disabled",
	danger_zone = "danger zone",
	delete_profile = "delete profile",
	delete_photo = "delete photo",
	delete_profile_mock_description = "delete profile mock description",
	disconnect = "disconnect",
	donuts_received = "weekly donuts received",
	donuts_sent = "weekly donuts sent",
	donuts_are_on_the_way = "donuts are on the way",
	domain = "domain",
	demo = "demo",
	donuts = "donuts",
	donut = "donut",
}
