export enum texts_e {
	enter_colleague_name = "enter colleague name",
	edit_circle = "edit circle",
	edit = "edit",
	error = "error",
	employees = "employees",
	employee = "employee",
	employment_date = "Employment date",
	empty_events_placeholder = "you dont have any events yet",
	expiration_date = "expiration date",
	expired = "expired",
	expires_in_days = "expires in {{count}} days",
	email_notification = "email notification",
	email_confirmation = "email confirmation",
	email_address = "email address",
	email_is_used_for_sign_in_and_notifications = "email is used for sign in and notifications",
	email_address_is_required = "email address is required",
	email_address_must_be_valid = "email address must be valid",
	every_week = "every week",
	every_month = "every month",
	edit_reward = "edit reward",
	edit_reward_description = "edit reward description",
}
