export enum texts_p {
	"profile" = "profile",
	"profiles" = "profiles",
	"price" = "price",
	"previous" = "previous",
	"preview" = "preview",
	purchase = "purchase",
	password = "password",
	password_repeat = "password_repeat",
	"page_not_found" = "page not found",
	password_changed = "password changed",
	password_is_required = "password is required",
	password_confirm_is_required = "password confirm is required",
	passwords_do_not_math = "password do not match",
}
