export enum texts_c {
	"close" = "close",
	"closed" = "closed",
	"cancel" = "cancel",
	"create" = "create",
	"created" = "created",
	"contact" = "Contact",
	"confirmation" = "confirmation",
	"confirm" = "confirm",
	"confirmed" = "confirmed",
	"confirm_email" = "confirm email",
	"closed_requests" = "closed requests",
	"choose_employees" = "choose employees",
	confirmation_email_was_sent_to = "confirmation email was sent to",
}
