export enum texts_i {
	in_top_most_active_percent = "in top most active percent",
	in_date = "in date",
	invitations = "invitations",
	invite_teammate = "invite teammate",
	incoming = "incoming",
	into_top_most_active_percent = "into top most active percent",
	i_can_spend = "i can spend",
	i_can_share = "i can share",
	integrations = "integrations",
	integration_channels = "integration channels",
	integration_email_description = "integration email description",
	integration_mattermost_description = "integration mattermost description",
	integration_telegram_description = "integration telegram description",
	integration_vk_description = "integration vk description",
}
