export enum texts_s {
	save = "save",
	search = "search",
	selected = "selected",
	show_only_mine = "show only mine",
	select_all = "select all",
	share = "share",
	selected_employees = "selected employees",
	set_password = "set password",
	send_confirmation_email = "send confirmation email",
	store_admin = "store admin",
	supply_days = "supply days",
	settings_updated = " settings updated",
	sign_in = "sign in",
	send = "send",
	sign_up = "sign_up",
	soon_will_be_back = "soon_will_be_back",
	scheduler_created = "scheduler created",
}
