export enum texts_i {
	in_top_most_active_percent = "in top most active percent",
	in_date = "in date",
	invitation_received = "invitation received",
	invitation_link_copied = "invitation link copied",
	invited_by = "invited by",
	invitations = "invitations",
	invite_teammate = "invite teammate",
	incoming = "incoming",
	join_teams_from_received_invitations = "join teams from received invitations",
	into_top_most_active_percent = "into top most active percent",
	i_can_spend = "i can spend",
	i_can_share = "i can share",
	integrations = "integrations",
	integration_channels = "integration channels",
	integration_email_description = "integration email description",
	integration_mattermost_description = "integration mattermost description",
	integration_telegram_description = "integration telegram description",
	integration_vk_description = "integration vk description",
	no_invitations_received_yet = "no invitations received yet",
	in_storefront = "in storefront",
	in_team_months = "in team months",
	in_team_years = "in team years",
}
