export enum texts_a {
	author = "author",
	auth_fill_required_fields = "auth fill required fields",
	auth_action_in_progress = "auth action in progress",
	accept = "accept",
	amount = "amount",
	approximate_action_time = "approximate action time",
	add_new_scheduler = "add new scheduler",
	admin_deposit = "admin deposit",
	add_comment = "add some comment",
	available_employees = "available employees",
	are_you_sure = "are you sure?",
	are_you_sure_to_delete = "are you sure to delete?",
	active = "active",
	active_request = "active requests",
	activated = "activated",
	activate = "activate",
	accepted = "accepted",
	access_denied = "access denied",
	all_invitations = "all invitations",
	add_colleague_to_team_invitation_description = "add colleague to team invitation description",
	admin = "admin",
	about_myself = "About myself",
	add_photo = "add photo",
}
