export enum BntRoutes {
	Login = "Login",
	Logout = "Logout",
	Registration = "Registration",
	Restore = "Restore",
	Recover = "Recover",
	Dashboard = "Dashboard",
	Donuts = "Donuts",
	DonutPreview = "DonutPreview",
	Profile = "Profile",
	Requests = "Requests",
	IncomingRequests = "IncomingRequests",
	ActiveRequests = "ActiveRequests",
	ClosedRequests = "ClosedRequests",
	People = "People",
	Settings = "Settings",
	Store = "Store",
	Schedulers = "Schedulers",
	Plugins = "Plugins",
	Share = "Share",
	Tenant = "Tenant",
	TenantList = "TenantList",
	Statistics = "Statistics",
	AccountOperations = "AccountOperations",
	MyRequests = "MyRequests",
	Home = "Home",
}
