export const BASE_URL = "https://id.vk.com/authorize";
export const VK_APP_ID = "54457672";
// export const VK_REDIRECT_URI = "https://develop.bonuts.ru/oauth/vk";
export const VK_CHALLENGE_METHOD = "S256";
export const VK_RESPONSE_TYPE = "code";
export const BASE_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
export const VK_CODE_LENGTH = 64;
export const VK_SCOPES = "phone email";
export const VK_REDIRECT_URI = "https://interzooecial-jean-subventrally.ngrok-free.dev/oauth/vk"; //"`${window.location.origin}`/oauth/vk";
